-- PostgreSQL Production Database Schema for Apex Brands — Amazon FBA Optimizer
-- Domain Architecture: Fleet Dispatch & Telematics Control (logistics)
-- Generated by BizzMitra AI Engine
-- Problem Statement Reference:
-- "We are an Amazon FBA seller managing 450+ ASINs across US and India marketplaces. We are suffering frequent stockouts on top-selling items during seasonal spikes, which crashes our Amazon Best Seller Rank (BSR) and costs us ~$45k/month in lost revenue. Simultaneously, our slow-moving SKUs are hitting 180+ day thresholds, costing $8,000/month in Amazon aged inventory surcharges. Our team is manually reconciling Amazon Seller Central Inventory CSVs in Excel with 3-week lead-time suppliers, leading to inaccurate reorder points and zero predictive visibility."

CREATE TABLE IF NOT EXISTS public.logistics_records (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  col1_data TEXT NOT NULL, -- Semantic Mapping: Origin → Destination Hub
  col2_data TEXT NOT NULL, -- Semantic Mapping: Fleet Vehicle & Speed
  status TEXT NOT NULL,    -- Semantic Mapping: Transit Status
  badge TEXT DEFAULT 'Active',
  assignee TEXT NOT NULL,  -- Semantic Mapping: Assigned Driver
  metric_value TEXT NOT NULL, -- Semantic Mapping: ETA Turnaround
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.logistics_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for demo application"
  ON public.logistics_records
  FOR ALL
  USING (true)
  WITH CHECK (true);
